Repository Gilead-BioStats/gsm, pull requests merged in 2023-09, with the labels that each got.

#1300 Release v1.8.1-rc2
  _pkgdown.yml
Labels: release

#1303 Release v1.8.1-rc4
  .github/workflows/pkgdown.yaml
  _pkgdown.yml
Labels: release

#1320 added a blank dataframe with the same column names contained in QTL r…
  R/CheckSnapshotInputs.R
  R/Make_Snapshot.R
Labels: bug

#1326 Fix 1325
  NAMESPACE
  R/Augment_Snapshot.R
  R/Study_Report.R
  R/Timeline.R
  R/util-ReportHelpers.R
  inst/report/KRIReportByCountry.Rmd
  inst/report/KRIReportByQTL.Rmd
  inst/report/KRIReportBySite.Rmd
  inst/report/styles.css
  inst/utils-0.0.1/showMetaTableDetails.js
  man/AssessStatus.Rd
  man/GetSnapshotDate.Rd
  man/MakeErrorLog.Rd
  man/MakeOverviewMessage.Rd
  man/MakeReportSetup.Rd
  man/MakeResultsTable.Rd
Labels: reporting
